# Generated by Django 2.1.7 on 2020-03-09 09:53

import account.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False, help_text='Flag for administrator account')),
                ('data_transfer_permission', models.BooleanField(default=True, help_text='Permission for individual users access to data transfer')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', account.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AWSRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='(Read-only) Date/time when record was created.')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='(Read-only) Date/time when record was updated.')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('D', 'Denied'), ('C', 'Completed')], default='P', help_text='Status of request', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='(Read-only) Date/time when record was created.')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='(Read-only) Date/time when record was updated.')),
                ('aws_user', models.CharField(help_text='AWS account username', max_length=155)),
                ('aws_access_key', models.CharField(help_text='AWS Access key id', max_length=255, unique=True)),
                ('aws_secret_access_key', models.CharField(help_text='AWS Secret key', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
