# Generated by Django 2.1.7 on 2020-02-06 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iam',
            old_name='access_key',
            new_name='aws_access_key',
        ),
        migrations.RenameField(
            model_name='iam',
            old_name='secret_access_key',
            new_name='aws_secret_access_key',
        ),
        migrations.RenameField(
            model_name='iam',
            old_name='username',
            new_name='aws_user',
        ),
    ]
