# Generated by Django 2.1.7 on 2020-02-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iam',
            name='aws_access_key',
            field=models.CharField(help_text='AWS Access key id', max_length=255, unique=True),
        ),
    ]
