# Generated by Django 2.1.7 on 2020-03-09 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iam',
            name='data_bucket',
            field=models.ForeignKey(blank=True, help_text='Bucket for dataset and config', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Bucket'),
        ),
        migrations.AddField(
            model_name='iam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='awsrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
