# Generated by Django 2.1.7 on 2020-02-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200217_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_transfer_permission',
            field=models.BooleanField(default=True, help_text='Permission for individual users access to data transfer'),
        ),
    ]
