# Generated by Django 2.1.7 on 2020-04-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200309_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iam',
            name='data_bucket',
        ),
    ]
