# Generated by Django 2.1.7 on 2020-02-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_data_transfer_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Flag for administrator account'),
        ),
    ]
