# Generated by Django 2.2.3 on 2020-05-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200511_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='name',
            field=models.CharField(help_text='Group Name', max_length=50, unique=True),
        ),
    ]
