# Generated by Django 2.2.1 on 2020-06-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200625_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_migrated_pwd',
            field=models.BooleanField(default=False),
        ),
    ]
