# Generated by Django 2.2.1 on 2020-08-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested_group_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
