# Generated by Django 2.2.1 on 2020-08-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200804_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='OOXUHE', max_length=6),
        ),
    ]
