# Generated by Django 2.2.1 on 2020-08-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200804_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='0A4441', max_length=6),
        ),
    ]
