# Generated by Django 2.2.1 on 2020-08-04 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20200804_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested_group_code',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AddField(
            model_name='user',
            name='use_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='877CA8', max_length=6),
        ),
    ]
