# Generated by Django 2.2.1 on 2020-08-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20200804_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='7C38E1', max_length=6),
        ),
    ]
