# Generated by Django 2.2.1 on 2020-08-05 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20200804_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='CA8D4F', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='requested_group_code',
            field=models.CharField(blank=True, default='', max_length=6, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='requested_group_name',
            field=models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
