# Generated by Django 2.2.1 on 2020-08-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20200805_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='B1AE24', max_length=6),
        ),
    ]
