# Generated by Django 2.2.1 on 2020-08-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20200805_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='0B8DA1', max_length=6),
        ),
    ]
