# Generated by Django 2.2.1 on 2020-08-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20200805_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='87AC26', max_length=6),
        ),
    ]
