# Generated by Django 2.2.1 on 2020-09-23 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20200805_0022'),
        ('account', '0010_auto_20200731_1741'),
    ]

    operations = [
    ]
