# Generated by Django 2.2.1 on 2020-10-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20201023_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='BECD8B', max_length=6),
        ),
    ]
