# Generated by Django 2.2.1 on 2021-03-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20201023_2030'),
        ('account', '0023_auto_20201028_0126'),
    ]

    operations = [
    ]
