# Generated by Django 2.2.1 on 2021-03-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_merge_20210330_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='54BBD6', max_length=6),
        ),
    ]
