# Generated by Django 2.2.1 on 2020-10-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20201023_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='F8A0C3', max_length=6),
        ),
    ]
