# Generated by Django 2.2.1 on 2021-03-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20210330_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='iam',
            name='aws_pwd',
            field=models.CharField(default='UNSET_CONTACT_ADMIN', help_text='AWS account password', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='420094', max_length=6),
        ),
    ]
