# Generated by Django 2.2.1 on 2020-10-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20201023_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='A8BEF6', max_length=6),
        ),
    ]
