# Generated by Django 2.2.1 on 2021-08-09 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20210403_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_added',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='6544EF', max_length=6),
        ),
    ]
