# Generated by Django 2.2.1 on 2021-08-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20210813_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='FC441F', max_length=6),
        ),
    ]
