# Generated by Django 2.2.24 on 2022-05-20 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20220519_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='88CF8D', max_length=6),
        ),
        migrations.CreateModel(
            name='TempObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='(Read-only) Date/time when record was created.')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='(Read-only) Date/time when record was updated.')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AnaGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
