# Generated by Django 2.2.24 on 2022-05-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_auto_20220520_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='8CC51C', max_length=6),
        ),
        migrations.DeleteModel(
            name='TempObject',
        ),
    ]
