# Generated by Django 2.2.24 on 2022-05-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_auto_20220520_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='8F2D38', max_length=6),
        ),
    ]
