# Generated by Django 2.2.24 on 2022-05-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_auto_20220520_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='iam',
            name='aws_session_token',
            field=models.CharField(blank=True, help_text='AWS session token', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='9FB821', max_length=6),
        ),
    ]
