# Generated by Django 2.2.24 on 2022-05-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_auto_20220520_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='A1B074', max_length=6),
        ),
        migrations.DeleteModel(
            name='AWSRequest',
        ),
    ]
