# Generated by Django 2.2.24 on 2022-05-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_auto_20220523_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='analyses',
            field=models.ManyToManyField(blank=True, to='main.Analysis'),
        ),
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='05A9B6', max_length=6),
        ),
    ]
