# Generated by Django 2.2.24 on 2022-05-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_auto_20220523_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='FB794A', max_length=6),
        ),
        migrations.AlterField(
            model_name='iam',
            name='aws_access_key',
            field=models.CharField(help_text='AWS Access key id', max_length=255),
        ),
    ]
