# Generated by Django 2.2.24 on 2022-05-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_auto_20220526_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iam',
            name='aws_pwd',
        ),
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='requested_group_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='requested_group_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='use_code',
        ),
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='CC21AF', max_length=6),
        ),
        migrations.AlterField(
            model_name='iam',
            name='aws_session_token',
            field=models.CharField(default='No token yet', help_text='AWS session token', max_length=255),
            preserve_default=False,
        ),
    ]
