# Generated by Django 2.2.24 on 2022-05-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_auto_20220527_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cred_expire',
        ),
        migrations.AddField(
            model_name='iam',
            name='cred_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='96AE4F', max_length=6),
        ),
    ]
