# Generated by Django 2.2.24 on 2022-05-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_auto_20220527_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default='656256', max_length=6),
        ),
        migrations.AlterField(
            model_name='iam',
            name='aws_user',
            field=models.CharField(blank=True, help_text='AWS account username', max_length=155, null=True),
        ),
    ]
