# Generated by Django 2.2.24 on 2022-05-27 19:36

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_auto_20220527_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagroup',
            name='code',
            field=models.CharField(default=account.models.group_uuid, max_length=6),
        ),
    ]
