# Generated by Django 2.2.24 on 2022-05-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_auto_20220527_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_migrated_pwd',
        ),
    ]
