# Generated by Django 2.2.24 on 2022-05-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_remove_user_has_migrated_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iam',
            name='cred_expire',
            field=models.DateTimeField(blank=True, help_text='Time Temporary Credentials Expire', null=True),
        ),
        migrations.AlterField(
            model_name='iam',
            name='fixed_creds',
            field=models.BooleanField(default=False, help_text='User Gets Permanent Credentials'),
        ),
    ]
