# Generated by Django 2.1.7 on 2020-03-09 09:53

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='(Read-only) Date/time when record was created.')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='(Read-only) Date/time when record was updated.')),
                ('name', models.CharField(help_text='Bucket name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of bucket', null=True)),
                ('algorithrm', models.CharField(blank=True, help_text='Algorithm name', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='(Read-only) Date/time when record was created.')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='(Read-only) Date/time when record was updated.')),
                ('name', models.CharField(help_text='File Name', max_length=100)),
                ('link', models.CharField(help_text='Link of S3 bucket', max_length=100)),
                ('uploaded', models.BooleanField(default=False, help_text='Flag to show complete of uploading')),
                ('bucket', models.ForeignKey(help_text='Bucket of file', on_delete=django.db.models.deletion.CASCADE, to='main.Bucket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='(Read-only) Date/time when record was created.')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='(Read-only) Date/time when record was updated.')),
                ('name', models.CharField(default=main.models.rand_id, help_text='Process name {Random Field}', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('F', 'Failed'), ('C', 'Completed')], default='P', help_text='Status of process', max_length=1)),
                ('s3_path', models.CharField(blank=True, help_text='Result path of s3', max_length=200, null=True)),
                ('local_file', models.CharField(blank=True, help_text='Result file of server', max_length=200, null=True)),
                ('iam', models.ForeignKey(help_text='User IAM for process', on_delete=django.db.models.deletion.CASCADE, to='account.IAM')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='(Read-only) Date/time when record was created.')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='(Read-only) Date/time when record was updated.')),
                ('name', models.CharField(default=main.models.rand_id, help_text='Subfolder name {Random Field}', max_length=100, unique=True)),
                ('bucket', models.ForeignKey(help_text='bucket', on_delete=django.db.models.deletion.CASCADE, to='main.Bucket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='process',
            name='subfolder',
            field=models.ForeignKey(blank=True, help_text='Subfolder of files', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SubFolder'),
        ),
        migrations.AddField(
            model_name='process',
            name='uploaded_file',
            field=models.ForeignKey(help_text='Uploaded json file', on_delete=django.db.models.deletion.CASCADE, to='main.FileItem'),
        ),
    ]
