# Generated by Django 2.1.7 on 2020-04-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='(Read-only) Date/time when record was created.')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='(Read-only) Date/time when record was updated.')),
                ('process_name', models.CharField(help_text='Name of Process', max_length=100, unique=True)),
                ('input_folder', models.CharField(help_text='Folder of dataset and config items', max_length=100)),
                ('result_prefix', models.CharField(help_text='Prefix of result folder name', max_length=100)),
                ('result_items', models.TextField(help_text='Json of result files')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
