# Generated by Django 2.1.7 on 2020-02-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='description',
            field=models.TextField(default='test', help_text='Description of bucket'),
            preserve_default=False,
        ),
    ]
