# Generated by Django 2.1.7 on 2020-02-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bucket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='description',
            field=models.TextField(blank=True, help_text='Description of bucket', null=True),
        ),
    ]
