# Generated by Django 2.1.7 on 2020-04-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='bucket_name',
            field=models.CharField(default='epi-ncap', help_text='Bucket Name', max_length=50),
            preserve_default=False,
        ),
    ]
