# Generated by Django 2.1.7 on 2020-02-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200217_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Algo',
            new_name='Algorithm',
        ),
    ]
