# Generated by Django 2.1.7 on 2020-02-17 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200217_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='(Read-only) Date/time when record was created.')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='(Read-only) Date/time when record was updated.')),
                ('name', models.CharField(default='a786ff26-5196-11ea-99c6-080027a268f4', help_text='Process name {Random Field}', max_length=100)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('F', 'Failed'), ('C', 'Completed')], default='P', help_text='Status of process', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Algorithm',
        ),
        migrations.RemoveField(
            model_name='fileitem',
            name='bucket',
        ),
        migrations.RemoveField(
            model_name='fileitem',
            name='sub_folder',
        ),
        migrations.AddField(
            model_name='bucket',
            name='algorithrm',
            field=models.CharField(default=1, help_text='Algorithm name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='bucket',
            field=models.ForeignKey(help_text='Bucket of files', on_delete=django.db.models.deletion.CASCADE, to='main.Bucket'),
        ),
        migrations.AddField(
            model_name='fileitem',
            name='process',
            field=models.ForeignKey(default=1, help_text='Process', on_delete=django.db.models.deletion.CASCADE, to='main.Process'),
            preserve_default=False,
        ),
    ]
