# Generated by Django 2.1.7 on 2020-02-17 15:36

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200217_1439'),
        ('main', '0006_auto_20200217_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='iam',
            field=models.ForeignKey(default=1, help_text='User IAM for process', on_delete=django.db.models.deletion.CASCADE, to='account.IAM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(default=main.models.rand_id, help_text='Process name {Random Field}', max_length=100, unique=True),
        ),
    ]
