# Generated by Django 2.1.7 on 2020-04-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_config_submit_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='input_folder',
        ),
        migrations.AddField(
            model_name='config',
            name='upload_folder',
            field=models.CharField(blank=True, help_text='Folder to upload dataset and config items', max_length=100, null=True),
        ),
    ]
