# Generated by Django 2.1.7 on 2020-02-18 01:50

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200217_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='(Read-only) Date/time when record was created.')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='(Read-only) Date/time when record was updated.')),
                ('name', models.CharField(default=main.models.rand_id, help_text='Subfolder name {Random Field}', max_length=100, unique=True)),
                ('bucket', models.ForeignKey(help_text='  of subfolder', on_delete=django.db.models.deletion.CASCADE, to='main.Bucket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='process',
            name='bucket',
        ),
        migrations.AddField(
            model_name='process',
            name='subfolder',
            field=models.ForeignKey(default=1, help_text='Subfolder of files', on_delete=django.db.models.deletion.CASCADE, to='main.SubFolder'),
            preserve_default=False,
        ),
    ]
