# Generated by Django 2.1.7 on 2020-04-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200407_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='(Read-only) Date/time when record was created.')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='(Read-only) Date/time when record was updated.')),
                ('analysis_name', models.CharField(help_text='Name of Process', max_length=100, unique=True)),
                ('upload_folder', models.CharField(blank=True, help_text='Folder to upload dataset and config items', max_length=100, null=True)),
                ('result_prefix', models.CharField(help_text='Prefix of result folder name', max_length=100)),
                ('result_items', models.TextField(help_text='Json of result files')),
                ('bucket_name', models.CharField(help_text='Bucket Name', max_length=100)),
                ('result_path', models.CharField(blank=True, help_text='Path of results', max_length=100, null=True)),
                ('config_path', models.CharField(blank=True, help_text='Path of config file', max_length=100, null=True)),
                ('dataset_path', models.CharField(blank=True, help_text='Path of dataset files', max_length=100, null=True)),
                ('submit_path', models.CharField(blank=True, help_text='Path of submit file', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Config',
        ),
    ]
