# Generated by Django 2.1.7 on 2020-04-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200414_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='bash_link',
            field=models.CharField(blank=True, help_text='Bash script link of Analysis', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='git_link',
            field=models.CharField(blank=True, help_text='Github link of Analysis', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='long_description',
            field=models.TextField(blank=True, help_text='Long description of analysis', null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='paper_link',
            field=models.CharField(blank=True, help_text='Link of Analysis Paper', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short description of analysis', null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='signature',
            field=models.TextField(blank=True, help_text='Signature of analysis', null=True),
        ),
    ]
