# Generated by Django 2.1.7 on 2020-02-20 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200218_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='subfolder',
            field=models.ForeignKey(blank=True, help_text='Subfolder of files', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SubFolder'),
        ),
        migrations.AlterField(
            model_name='subfolder',
            name='bucket',
            field=models.ForeignKey(help_text='bucket', on_delete=django.db.models.deletion.CASCADE, to='main.Bucket'),
        ),
    ]
