# Generated by Django 2.1.7 on 2020-02-20 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200220_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileitem',
            name='iam',
        ),
        migrations.RemoveField(
            model_name='fileitem',
            name='process',
        ),
        migrations.RemoveField(
            model_name='fileitem',
            name='size',
        ),
        migrations.AddField(
            model_name='fileitem',
            name='bucket',
            field=models.ForeignKey(default=1, help_text='Bucket of file', on_delete=django.db.models.deletion.CASCADE, to='main.Bucket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='uploaded_file',
            field=models.ForeignKey(default=1, help_text='Uploaded json file', on_delete=django.db.models.deletion.CASCADE, to='main.FileItem'),
            preserve_default=False,
        ),
    ]
