# Generated by Django 2.2.3 on 2020-05-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200511_2301'),
        ('main', '0011_analysis_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='groups',
        ),
        migrations.AddField(
            model_name='analysis',
            name='groups',
            field=models.ManyToManyField(to='account.AnaGroup'),
        ),
    ]
