# Generated by Django 2.2.3 on 2020-05-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200511_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileitem',
            name='bucket',
        ),
        migrations.RemoveField(
            model_name='process',
            name='iam',
        ),
        migrations.RemoveField(
            model_name='process',
            name='subfolder',
        ),
        migrations.RemoveField(
            model_name='process',
            name='uploaded_file',
        ),
        migrations.RemoveField(
            model_name='subfolder',
            name='bucket',
        ),
        migrations.DeleteModel(
            name='Bucket',
        ),
        migrations.DeleteModel(
            name='FileItem',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.DeleteModel(
            name='SubFolder',
        ),
    ]
