# Generated by Django 2.2.3 on 2020-05-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200512_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='demo_link',
            field=models.TextField(blank=True, help_text='Link of Demo page', null=True),
        ),
    ]
