# Generated by Django 2.2.3 on 2020-05-27 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_analysis_demo_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name_plural': 'Analyses'},
        ),
    ]
