# Generated by Django 2.2.3 on 2020-05-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200527_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='custom',
            field=models.BooleanField(default=False, help_text='Custom Analysis option'),
        ),
    ]
