# Generated by Django 2.2.1 on 2021-08-13 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210813_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='result_prefix',
            field=models.CharField(help_text='Prefix of result folder name. FORMAT: job__bucketName_', max_length=100, validators=[django.core.validators.RegexValidator('^job__.+_$', 'Input needs to match format job__bucketname_.')]),
        ),
    ]
